development:
  adapter: mysql2
  database: webeetle_dev
  encoding: utf8
  username: root
  password: ''
  host: 127.0.0.1
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  database: webeetle_test
  username: root
  password: ''
  host: 127.0.0.1
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: webeetle
  pool: 5
  username: root
  password: ''